# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.servicefactory:
        class: AppBundle\Service\ServiceFactory
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]
    app.userservice:
        class: AppBundle\Service\UserService
        factory: ["@app.servicefactory", getUserService]
    app.depotservice:
        class: AppBundle\Service\DepotService
        factory: ["@app.servicefactory", getDepotService]
    app.parcelservice:
        class: AppBundle\Service\ParcelService
        factory: ["@app.servicefactory", getParcelService]
    app.statusservice:
        class: AppBundle\Service\StatusService
        factory: ["@app.servicefactory", getStatusService]
    app.addressservice:
        class: AppBundle\Service\AddressService
        factory: ["@app.servicefactory", getAddressService]
